mixed-port: 7890
allow-lan: true
log-level: info
external-controller: 127.0.0.1:50912
secret: 'b8b3a0d6-0c3c-44d2-8f80-0c0f699abf99'
ipv6: true

# Will be ignored after profile selection
proxies:
  - name: Debug
    type: socks5
    server: 127.0.0.1
    port: 1080
proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - Debug
rules:
  - 'MATCH,DIRECT'
